
def Generate_waveform(AWG, amplitude, frequency, num_pulses, channel, AnalogComp=False, Stuck_Low=False, Stuck_high=False):
    """
    Configures the AWG to generate pulse waveforms on the specified channels.
    
    Parameters:
    - AWG: VISA resource handle to the AWG.
    - amplitude: Amplitude of the waveform in volts.
    - offset: Offset of the waveform in volts.
    - frequency: Frequency of the pulse waveform in Hz.
    - num_pulses: Number of pulses to generate.
    - channel: Channel(s) to configure.
    """
    from Configure_Instrument.SetUp_AWG import flush_errors
    from Configure_Instrument.SetUp_AWG import Reset_Instrument
    from Configure_Instrument.SetUp_AWG import close_awg_connection
    import numpy as np
    import matplotlib.pyplot as plt
    import time

    def write_cmd(cmd):
        AWG.write(cmd)
        # print(cmd)
        # flush_errors(AWG)
    def build_waveform(waveform_type, sample_num=256):
        byte_samples = bytearray(2 * sample_num)

        for i in range(sample_num):

            # ---------------- SQUARE ----------------
            if waveform_type == "square":
                reversed_i = sample_num - 1 - i
                if (i < sample_num / 2):
                    func = 0
                else:
                    func = 32786

            # --------  TRIANGULAR ----------
            elif waveform_type == "tri_stuck_low":
                if i < sample_num // 2:
                    x = i / (sample_num // 2)
                    tri = -1.0 + 2.0 * x
                else:
                    x = (i - sample_num // 2) / (sample_num // 2)
                    tri = 1.0 - 2.0 * x

                func = int((tri + 1.0) * 16383)

            # --------  Sine ----------
            elif waveform_type == "sine_stuck_high":
                angle = 2 * np.pi * i / sample_num
                sine = np.sin(angle)              # [-1, +1]
                func = int((sine + 1.0) * 16383)  # [0 .. 32766]

            else:
                raise ValueError(f"Unknown waveform type: {waveform_type}")

            # -------- PACK TO DAC --------
            func = max(0, min(32767, func))
            byte_samples[2 * i]     = func & 0xFF
            byte_samples[2 * i + 1] = (func >> 8) & 0xFF

        return byte_samples


    def Plot_Samples(waveformbytes):

        waveform_data = np.empty(int(len(waveformbytes)/2))

        for i in range(0, len(waveform_data)):
            waveform_data[len(waveform_data) - i -
                          1] = waveformbytes[2*i] + waveformbytes[2*i+1]*256

        # Convert waveform data to numpy array for visualization
        # Plot the waveform
        plt.figure()
        plt.plot(waveform_data)  # Plot the first 1000 points for visibility
        plt.title("Pulse Waveform Generated by AWG")
        plt.xlabel("Time (s)")
        plt.ylabel("Amplitude (V)")
        plt.grid(True)
        plt.show()
    # end of def Plot_Samples(waveformbytes):

    if AnalogComp:
        #write_cmd(f"AFGControl:STOP ") # Stop the AWG before pulse generation
        #time.sleep(0.1)
        # Ensure all variables are lists, even if provided as single values
        channel = [channel] if isinstance(channel, int) else channel
        amplitude = [amplitude] if isinstance(
            amplitude, (int, float)) else amplitude
        # offset = [offset] if isinstance(offset, (int, float)) else offset

        # Use free channel for trigger
        # Add channel 5 to the list (if not already included)
        if 5 not in channel:
            channel.append(5)

        # Disable the output for the channel
        # for i in range(1, 9):
            # write_cmd(f"OUTPut{i}:IMPedance MAXimum")
            # write_cmd(f"OUTPut{i}:STATe 0")

        # Check if the Current status of Generator is running
        current_state = AWG.query(f"AFGControl:STATus?")
        if int(current_state) == 1:  # If the Generator is on
            #print(f"AWG is in Run mode, Turning it off...")
            write_cmd(f"AFGControl:STOP ")  # Stop the Generator

        for selected_channel in channel:

            # Calculate waveform parameters
            sample_num = 256  # Number of samples per pulse
            
            # Create a pulse waveform
            byte_samples = bytearray(2 * sample_num)  # Declare the array of bytes
            for i in range(0, sample_num - 1):
                # print(i)
                reversed_i = sample_num - 1 - i
                if (reversed_i < sample_num / 2):
                    func = 0
                else:
                    func = 32786

                byte_samples[2 * i] = int(func % 256)  # Lower
                byte_samples[2 * i + 1] = int(func / 256)  # upper
            
            
            # Generate sine waveform
            # for i in range(sample_num):
            #     angle = 2 * np.pi * i / sample_num
            #     sine_value = np.sin(angle)
            #     scaled = int((sine_value + 1) * 16383)  # Scale to 14-bit unsigned range (0 to ~32766)
            #     byte_samples[2 * i] = scaled & 0xFF  # Lower byte
            #     byte_samples[2 * i + 1] = (scaled >> 8) & 0xFF  # Upper byte
            
            print(f"Configuring AWG channel {selected_channel}...")

            # Disable the output for the channel
            write_cmd(f"OUTPut{selected_channel}:STATe 0")

            # Set the voltage limit for each channel
            write_cmd(f"SOURce{selected_channel}:VOLTage:LIMit:HIGH 200mV ")

            # Sets the channel load impedance to maximum
            write_cmd(f"OUTPut{selected_channel}:LOAd MAXimum")

            # print("Buffer for TRACE expects n points:\n", AWG.query(f'TRACE{selected_channel}:POINTS?'))

            # Send waveform data to the channel
            str_cmd = f'TRACe{selected_channel}:DATA CAR,'
            # AWG.write_binary_values(str_cmd, byte_samples, datatype='B', is_big_endian=True)
            AWG.write_binary_values(str_cmd, byte_samples, datatype='B')

            # To Plot the samples
            # waveformbytes = AWG.query_binary_values( f'TRACe{selected_channel}:DATA? CAR', datatype='B')
            # Plot_Samples(waveformbytes)

            # Set arbitrary waveform
            write_cmd(f"SOURce{selected_channel}:FUNCtion:SHAPe ARBB")

            if amplitude[selected_channel-1] > 0:
                write_cmd(
                    f"SOURce{selected_channel}:VOLTage:AMPLitude {amplitude[selected_channel-1]}")
                # write_cmd(f"SOURce{selected_channel}:VOLTage:HIGH {amplitude}")
                # write_cmd(f"SOURce{selected_channel}:VOLTage:LOW 0")

                # Set offset, both of the following commands work
                write_cmd(f"SOURce{selected_channel}:VOLTage:OFFSet {amplitude[selected_channel-1]/2}") # For pulse waveform this should be uncommented
                #write_cmd(f"SOURce{selected_channel}:VOLTage:OFFSet 0")   #True  only for sine wave
                
            else:
                write_cmd(f"SOURce{selected_channel}:VOLTage:HIGH 0")
                write_cmd(
                    f"SOURce{selected_channel}:VOLTage:LOW {amplitude[selected_channel-1]}")

                # Set offset, both of the following commands work
                write_cmd(f"SOURce{selected_channel}:VOLTage:OFFSet {amplitude[selected_channel-1]/2}") # For pulse wave form 
                #write_cmd(f"SOURce{selected_channel}:VOLTage:OFFSet 0") # True only for sine wave

            # Set offset
            # write_cmd(f"SOURce{selected_channel}:VOLTage:OFFSet {offset}")
            # write_cmd(f"SOURce{selected_channel}:VOLTage:OFFSet {amplitude[selected_channel-1]/2}")
            # Amplitude
            # write_cmd(f"SOURce{selected_channel}:VOLTage:AMPLitude {amplitude[selected_channel-1]}")

            # #Set the Pulse  Frequency
            write_cmd(f"SOURce{selected_channel}:FREQuency  {frequency}kHz  ")

            # before generating pulse the instrument waits for a trigger event.
            write_cmd(f"SOURce{selected_channel}:RUNMode BURSt ")

            # #The number of cycles (burst length) to be output
            write_cmd(f"SOURce{selected_channel}:BURSt:NCYCles {num_pulses} ")

            # BurstMode Trigger
            write_cmd(f"SOURce{selected_channel}:BURSt:MODE TRIGgered")

            # Base Line Offset
            write_cmd(f"SOURce{selected_channel}:VOLTage:BASELINE:OFFSET 0 ")

            # Enable the output for the channel
            write_cmd(f"OUTPut{selected_channel}:STATe 1")
 
    # waveform (any shape) generation to program memristor, read resistance after pulse and reset
    else:
    
        write_cmd(f"AFGControl:STOP ") # Stop the AWG before pulse generation
        time.sleep(0.1)
        # Ensure all variables are lists, even if provided as single values
        channel = [channel] if isinstance(channel, int) else channel
        #write_cmd(f"SYSTem:KCLick:STATe OFF") # Click sound disable 

        # Add channel 5 to the list (if not already included), Use free channel for trigger
        if 5 not in channel:
            channel.append(5)
        #if 8 not in channel:
           # channel.append(8)
        
        # Disable the output for the channel is this line is useful ???
        #for i in range(1, 6):
            #write_cmd(f"OUTPut{i}:STATe OFF")            
         
        # Check if the Current status of Generator is on
        current_state = AWG.query(f"AFGControl:STATus?")
        #if int(current_state) == 1:  # If the Generator is on
            #print(f"AWG is in Run mode, Turning it off...")
            #write_cmd(f"AFGControl:STOP ")  # Stop the Generator

        for selected_channel in channel:
            if Stuck_high:
                waveform = "sine_stuck_high"
            elif Stuck_Low:
                waveform = "tri_stuck_low"
            else:
                waveform = "square"

            byte_samples = build_waveform(waveform, sample_num=256)
            # Disable the output for the channel
            #write_cmd(f"OUTPut{selected_channel}:STATe OFF")

            # Set the voltage limit for each channel
            write_cmd(f"SOURce{selected_channel}:VOLTage:LIMit:HIGH 1.5 V ")

            # Sets the channel load impedance to maximum
            write_cmd(f"OUTPut{selected_channel}:LOAd:IMPedance MAX")
            write_cmd(f"OUTPut{selected_channel}:LOW:IMPedance OFF") # On = 5 ohm, Off = 50 ohm      
            # sets or returns the Output Impedance of the analog channel n
            #write_cmd(f"OUTPut{selected_channel}:OUTPut1:SERies:IMPedance 50Ohm ")            

            # print("Buffer for TRACE expects n points:\n", AWG.query(f'TRACE{selected_channel}:POINTS?'))

            # Send waveform data to the channel
            str_cmd = f'TRACe{selected_channel}:DATA CAR,'
            # AWG.write_binary_values(str_cmd, byte_samples, datatype='B', is_big_endian=True)
            AWG.write_binary_values(str_cmd, byte_samples, datatype='B')

            # To Plot the samples
            # waveformbytes = AWG.query_binary_values( f'TRACe{selected_channel}:DATA? CAR', datatype='B')
            # Plot_Samples(waveformbytes)

            # Set arbitrary waveform
            write_cmd(f"SOURce{selected_channel}:FUNCtion:SHAPe ARBB")

            # Set absolute amplitude
            A = abs(amplitude)

            # ---------------- NORMAL PROGRAMMING ----------------
            if not Stuck_Low and not Stuck_high:

                if amplitude >= 0:
                    # Unipolar positive pulse: 0 → +A
                    write_cmd(f"SOURce{selected_channel}:VOLTage:HIGH {A}")
                    write_cmd(f"SOURce{selected_channel}:VOLTage:LOW 0")
                    write_cmd(f"SOURce{selected_channel}:VOLTage:OFFSet {A/2}")

                else:
                    # Unipolar negative pulse: 0 → -A
                    write_cmd(f"SOURce{selected_channel}:VOLTage:HIGH 0")
                    write_cmd(f"SOURce{selected_channel}:VOLTage:LOW {-A}")
                    write_cmd(f"SOURce{selected_channel}:VOLTage:OFFSet {-A/2}")

            # ---------------- STUCK-LOW RECOVERY ----------------
            elif Stuck_Low and not Stuck_high:

                # Symmetric bipolar waveform (gentle forming)
                write_cmd(f"SOURce{selected_channel}:VOLTage:HIGH {A}")
                write_cmd(f"SOURce{selected_channel}:VOLTage:LOW {-A}")
                write_cmd(f"SOURce{selected_channel}:VOLTage:OFFSet 0")

            # ---------------- STUCK-HIGH RECOVERY ----------------
            elif Stuck_high and not Stuck_Low:
                write_cmd(f"SOURce{selected_channel}:VOLTage:HIGH {A}")
                write_cmd(f"SOURce{selected_channel}:VOLTage:LOW {-A}")
                write_cmd(f"SOURce{selected_channel}:VOLTage:OFFSet {-A*2}")

            else:
                raise RuntimeError("Invalid stuck state: both stuck_low and stuck_high are True")
                        
            # Set the Pulse  Frequency
            write_cmd(f"SOURce{selected_channel}:FREQuency  {frequency}KHz  ")

            # #before generating the instrument waits for a trigger event.
            write_cmd(f"SOURce{selected_channel}:RUNMode BURSt ")

            # #The number of cycles (burst length) to be output
            write_cmd(f"SOURce{selected_channel}:BURSt:NCYCles {num_pulses} ")

            # BurstMode Trigger
            write_cmd(f"SOURce{selected_channel}:BURSt:MODE TRIGgered")

            # Base Line Offset
            write_cmd(f"SOURce{selected_channel}:VOLTage:BASELINE:OFFSET 0 ")

            # Enable the output for the channel
            write_cmd(f"OUTPut{selected_channel}:STATe ON")
    # External Trigger
    # write_cmd("TRIGger:SOURce EXTernal")  # Set trigger to (External Trigger)
    write_cmd("TRIGger:SOURce MANual")  
    # Marker for trigger, link marker 3 to chanel 5
    write_cmd("MARKer:LINk3 CCH1")

    write_cmd("TRIGger:SLOPe RISING")
    write_cmd("TRIGger:IMPedance 50Ohm ")  # Trigger input impedance
    # sets the external trigger-in threshold level to 0.5 V
    write_cmd("TRIGger:SEQuence:THREshold 1.0V ")

   # start the instrument to arm for the trigger
    write_cmd("AFGControl:START")  # Start the AWG
    time.sleep(0.1)
    # Fires the trigger
    write_cmd("TRIGger:SEQuence:IMMediate") 
    
    
    # Small delay to ensure command is processed  
    #time.sleep(0.2)
    #write_cmd(f"AFGControl:STOP ") # Stop the AWG after pulse generation
    